### ISSUE TITLE
Config Server Failure (How to Manually Configure?)

### ISSUE THREAD

**Issue by joehand** [dokku-alt/dokku-alt#209]
The installation of Dokku works fine until I try to go the the configuration site (e.g. example.com:2000). This is on a brand new DigitalOcean Ubuntu 14.04 Droplet (tried destroying/new droplets several times w/ same result). The site won't load and I get this message:

```
== Sinatra/1.4.3 has taken the stage on 2000 for production with backup from WEBrick
[2015-02-27 16:09:29] INFO  WEBrick::HTTPServer#start: pid=28995 port=2000
[2015-02-27 16:09:32] ERROR Errno::ECONNRESET: Connection reset by peer
	/usr/lib/ruby/1.9.1/webrick/httpserver.rb:80:in `eof?'
	/usr/lib/ruby/1.9.1/webrick/httpserver.rb:80:in `run'
	/usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

I've tried the manual configuration but still can't get Dokku working properly (the instructions are a bit lacking there). 

The only page that loads in the main domain (example.com), which shows the NGIX welcome page. No other apps work. The VHOST file has the correct domain.

`dokku status node-js-app` says `stopped`, even after I start it or rebuild it.

How do I manually configure Dokku? Or what can I do to make the automatic config work?

**Comment by ayufan** [comment]
Can you show how looks build log when you deploy app?

**Comment by joehand** [comment]
Sure, this is the node-js-app:

```
[master][~/Downloads/node-js-sample]$ git push dokku master                         
Counting objects: 378, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (307/307), done.
Writing objects: 100% (378/378), 211.25 KiB | 0 bytes/s, done.
Total 378 (delta 42), reused 378 (delta 42)
remote: Cloning into '/tmp/tmp.UMMmk6xRov'...
remote: warning: You appear to have cloned an empty repository.
remote: done.
remote: HEAD is now at 97a7c5c... wording
remote: -----> Building node-js-app using buildstep...
remote: Unable to find image 'ayufan/dokku-alt-buildstep:cedar-14' locally
remote: Pulling repository ayufan/dokku-alt-buildstep
remote: e489a5237673: Pulling image (cedar-14) from ayufan/dokku-alt-buildstep
remote: e489a5237673: Pulling image (cedar-14) from ayufan/dokku-alt-buildstep, endpoint: https://registry-1.docker.io/v1/
remote: e489a5237673: Pulling dependent layers
remote: 511136ea3c5a: Download complete
remote: ed53cd6f7f21: Pulling metadata
remote: ed53cd6f7f21: Pulling fs layer
remote: ed53cd6f7f21: Download complete
remote: 6370e261ca45: Pulling metadata
remote: 6370e261ca45: Pulling fs layer
remote: 6370e261ca45: Download complete
remote: 76884e4bb2dc: Pulling metadata
remote: 76884e4bb2dc: Pulling fs layer
remote: 76884e4bb2dc: Download complete
remote: 1a8285f79dbb: Pulling metadata
remote: 1a8285f79dbb: Pulling fs layer
remote: 1a8285f79dbb: Download complete
remote: d196c562e50f: Pulling metadata
remote: d196c562e50f: Pulling fs layer
remote: d196c562e50f: Download complete
remote: 3dc9263948d9: Pulling metadata
remote: 3dc9263948d9: Pulling fs layer
remote: 3dc9263948d9: Download complete
remote: 5a81e3c2228f: Pulling metadata
remote: 5a81e3c2228f: Pulling fs layer
remote: 5a81e3c2228f: Download complete
remote: bd73746b0145: Pulling metadata
remote: bd73746b0145: Pulling fs layer
remote: bd73746b0145: Download complete
remote: e67e65976621: Pulling metadata
remote: e67e65976621: Pulling fs layer
remote: e67e65976621: Download complete
remote: d8774a75311a: Pulling metadata
remote: d8774a75311a: Pulling fs layer
remote: d8774a75311a: Download complete
remote: ee9011f589bf: Pulling metadata
remote: ee9011f589bf: Pulling fs layer
remote: ee9011f589bf: Download complete
remote: e489a5237673: Pulling metadata
remote: e489a5237673: Pulling fs layer
remote: e489a5237673: Download complete
remote: e489a5237673: Download complete
remote: Status: Downloaded newer image for ayufan/dokku-alt-buildstep:cedar-14
remote: -----> Installing ENV in build environment ...
-----> Using u1000 to run an application
-----> Node.js app detected
-----> Requested node range: 0.10.x
-----> Resolved node version: 0.10.36
-----> Downloading and installing node
-----> Exporting config vars to environment
-----> Installing dependencies
       express@4.12.0 node_modules/express
       ├── merge-descriptors@0.0.2
       ├── utils-merge@1.0.0
       ├── cookie-signature@1.0.6
       ├── methods@1.1.1
       ├── fresh@0.2.4
       ├── cookie@0.1.2
       ├── escape-html@1.0.1
       ├── range-parser@1.0.2
       ├── content-type@1.0.1
       ├── finalhandler@0.3.3
       ├── vary@1.0.0
       ├── parseurl@1.3.0
       ├── serve-static@1.9.1
       ├── content-disposition@0.5.0
       ├── path-to-regexp@0.1.3
       ├── depd@1.0.0
       ├── qs@2.3.3
       ├── on-finished@2.2.0 (ee-first@1.1.0)
       ├── debug@2.1.1 (ms@0.6.2)
       ├── proxy-addr@1.0.6 (forwarded@0.1.0, ipaddr.js@0.1.8)
       ├── etag@1.5.1 (crc@3.2.1)
       ├── send@0.12.1 (destroy@1.0.3, ms@0.7.0, mime@1.3.4)
       ├── type-is@1.6.0 (media-typer@0.3.0, mime-types@2.0.9)
       └── accepts@1.2.4 (negotiator@0.5.1, mime-types@2.0.9)
-----> Caching node_modules directory for future builds
-----> Cleaning up node-gyp and npm artifacts
-----> No Procfile found; Adding npm start to new Procfile
-----> Building runtime environment
-----> Discovering process types
       Procfile declares types -> web
remote: -----> Injecting git revision
remote: -----> Releasing node-js-app ...
remote: -----> Deploying node-js-app ...
remote: -----> Shutting down old containers
remote: =====> Application deployed:
remote:        http://node-js-app.example.com
remote: -----> Cleaning up ...
To dokku@example.com:node-js-app
 * [new branch]      master -> master
```

**Comment by ayufan** [comment]
Everything looks ok.

What does show: `dokku logs node-js-app`, `docker ps -a`?

**Comment by ayufan** [comment]
@joehand please join: https://gitter.im/dokku-alt/dokku-alt

**Comment by kjschulz** [comment]
:+1: Configuration ruby script never loads on port 2000
